# TODO: https://bsideup.github.io/posts/local_development_with_testcontainers/

version: '3'
services:
  minio:
    image: minio/minio:RELEASE.2020-10-09T22-55-05Z
    container_name: zm-minio
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: test
      MINIO_SECRET_KEY: testtest
      MINIO_NOTIFY_WEBHOOK_ENABLE_zm: "on"
      MINIO_NOTIFY_WEBHOOK_ENDPOINT_zm: "http://host.docker.internal:8080/index/webhook"
    command: server /data
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    container_name: zm-elastic
    ports:
      - 9200:9200
    environment:
      discovery.type: single-node
      http.cors.enabled: 'true'
      http.cors.allow-origin: '*'
      ES_JAVA_OPTS: -Xms750m -Xmx750m
  imaginary:
    image: h2non/imaginary:1.2.4
    container_name: zm-imaginary
    ports:
      - 9100:9100
    environment:
      PORT: 9100
      DEBUG: "*"
