version: '3'
services:
  minio:
    image: minio/minio:RELEASE.2020-10-09T22-55-05Z
    container_name: zm-minio-test
    environment:
      MINIO_ACCESS_KEY: test
      MINIO_SECRET_KEY: testtest
    command: server /data
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    container_name: zm-elastic-test
    environment:
      - discovery.type=single-node
      - http.cors.enabled=true
      - http.cors.allow-origin=*
  imaginary:
    image: h2non/imaginary:1.2.4
    container_name: zm-imaginary-test
    environment:
      PORT: 9000
      DEBUG: "*"
  zeitmaschine:
    image: maven:3.6-openjdk-14-slim
    command: mvn verify -Pintegration-tests

