s3:
    host: http://localhost:9000
    webhook: true
    access:
        key: "test"
        secret: "testtest"
elasticsearch:
    host: http://localhost:9200
    index: "zeitmaschine"
    resource: "image"

spring:
    security:
        oauth2:
            resourceserver:
                id: http://localhost:8080/
                jwk:
                    jwk-set-uri: https://zeitmaschine.eu.auth0.com/.well-known/jwks.json
                    issuer-uri: https://zeitmaschine.eu.auth0.com/
---

spring:
    profiles: production
logging:
    file: /var/log/zeitmaschine/zeitmaschine.log
s3:
    host: http://s3.zeitmaschine.netz
elasticsearch:
    host: http://elastic.zeitmaschine.netz
