s3:
    host: http://localhost:9000
    bucket: media
    cache-bucket: media-cache
    webhook: true
    access:
        key: "test"
        secret: "testtest"
elasticsearch:
    host: http://localhost:9200
    index: "zeitmaschine"
    resource: "image"
imaginary:
    host: http://localhost:9100

spring:
    security:
        oauth2:
            resourceserver:
                id: http://localhost:8080/
                jwk:
                    jwk-set-uri: https://zeitmaschine.eu.auth0.com/.well-known/jwks.json
                    issuer-uri: https://zeitmaschine.eu.auth0.com/
management:
    endpoint:
        health:
            enabled: true
            probes:
                enabled: true
            show-details: always

---

spring:
    profiles: production
logging:
    file:
        name: /var/log/zeitmaschine/zeitmaschine.log
s3:
    host: http://s3.zeitmaschine.netz
elasticsearch:
    host: http://elastic.zeitmaschine.netz
imaginary:
    host: http://zeitmaschine:9100
