s3:
    host: http://localhost:9000
    access:
        key: "test"
        secret: "testtest"
elasticsearch:
    host: http://localhost:9200
    index: "zeitmaschine"
    resource: "image"
---

spring:
    profiles: production
logging:
    file: /var/log/zeitmaschine/zeitmaschine.log
