# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: 17
    - name: Run integration tests
      run: mvn clean verify -U -Pintegration-tests
    - name: Deploy maven artifact and container
      run: mvn deploy -DskipTests jib:build -Djib.to.auth.username=espen-j -Djib.to.auth.password=${{ secrets.GHCR_TOKEN }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
